### ISSUE TITLE
ERROR Asset render failed: lib/three/gulpfile.js

### ISSUE THREAD

**Issue by MoshiCoCo** [Rozbo/hexo-neat#9]
```
ERROR Asset render failed: lib/three/gulpfile.js
Error
    at new JS_Parse_Error (eval at <anonymous> (D:\hexover\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1534:18)
    at js_error (eval at <anonymous> (D:\hexover\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1542:11)
    at croak (eval at <anonymous> (D:\hexover\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2089:9)
    at token_error (eval at <anonymous> (D:\hexover\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2097:9)
    at unexpected (eval at <anonymous> (D:\hexover\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2103:9)
    at expr_atom (eval at <anonymous> (D:\hexover\node_modules\hexo-neat\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2618:13)

```

不知道是不是之前装过 GULP压缩的问题，另外页面中的动态背景也失效凉了

**Comment by MoshiCoCo** [comment]
已经解决了 因为之前安装过gulp，然后在`package.json`中移除了，但是`theme/next/source/three/`中有之前使用gulp压缩静态文件生成的`gulpfile.js`文件，使用`hexo g`进行渲染的时候，这个js文件无法被渲染，所以报错。

**Comment by ListenV** [comment]
我也遇到同样问题，不过按照楼上的方法也解决了

**Comment by yumdeer** [comment]
> 我也遇到同样问题，不过按照楼上的方法也解决了

知道了问题不知道怎么解决😂，老哥请问下具体操作是什么？

**Comment by MoshiCoCo** [comment]
> > 我也遇到同样问题，不过按照楼上的方法也解决了
> 
> 知道了问题不知道怎么解决😂，老哥请问下具体操作是什么？

移除theme/next/source/three/中之前使用gulp压缩静态文件生成的’gulpfile.js’文件

也可能是其他文件，按照报错无法渲染的文件移除就可以。
